services:
  - type: web
    name: n8n-estoque
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: N8N_HOST
        value: 0.0.0.0
